brainvita_frontend/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import accounts.urls
import profiles.urls
import dashboard.urls
import mysite.urls
import delegate.urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profiles.urls, namespace='profiles')),
    url(r'^users/', include(dashboard.urls, namespace='dashboard')),
    url(r'^tester/', include(delegate.urls, namespace='tester')),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(mysite.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url

from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^home/$', views.HomeView.as_view(), name='home_view'),
    url(r'^vision/$', views.VisionView.as_view(), name='vision_view'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard_view'),
    url(r'^dashboard/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.DashboardView.as_view(), name='dashboard_view'),
    url(r'^create_test_view/$', views.CreateTestView.as_view(), name='create_test_view'),
    url(r'^create_test_view/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.CreateTestView.as_view(), name='create_test_view'),
    url(r'^project_overview/$', views.ProjectView.as_view(), name='project_overview'),
    url(r'^project_overview/(?P<project_id>[0-9]+)$', views.ProjectView.as_view(), name='test_view'),
    url(r'^add_project/$', views.AddProjectView.as_view(), name='add_project'),
    url(r'^add_project/(?P<project_id>[0-9]+)$', views.AddProjectView.as_view(), name='edit_project'),
    url(r'^add_test/$', views.AddTestView.as_view(), name='add_test'),
    url(r'^edit_test/$', views.EditTestView.as_view(), name='edit_test'),
    url(r'^add_media/(?P<project_id>[0-9]+)$', views.AddMediaView.as_view(), name='add_media'),
    url(r'^manage_project/$', views.ManageProjectView.as_view(), name='manage_project'),
    url(r'^media_overview/$', views.MediaView.as_view(), name='media_overview'),
    url(r'^media_overview_list/(?P<project_id>[0-9]+)$', views.MediaOverview.as_view(), name='media_overview_list'),
    url(r'^media_overview_report/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.MediaReportsView.as_view(), name='media_overview_report'),
    url(r'^view_reports/$', views.ReportsView.as_view(), name='view_reports'),
    url(r'^compare_reports/$', views.CompareReportsView.as_view(), name='compare_reports'),
    url(r'^track_test/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.TestDetails.as_view(), name='track_test'),
    url(r'^uploadfile/(?P<media_id>[0-9]+)$', views.UploadFile.as_view(), name='uploadfile'),
    url(r'^s3uploadvideo/', views.S3FileUploadAPI.as_view(), name='s3uploadvideo'),
    url(r'^settings/$', views.SettingsView.as_view(), name='settings'),

]

delegate/urls.py
from django.conf.urls import url
from delegate.views import *
urlpatterns = [
    url(r'^signup/(?P<uuid>.+)$', SignUpView.as_view(), name='signup'),
    # url(r'^home_view/$', HomeView.as_view(), name='home_view'),
    # url(r'^dashboard_view/$', DashboardView.as_view(), name='dashboard_view'),
    # url(r'^login/$', LoginView.as_view(), name="login"),
    # url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # url(r'^password-change/$', PasswordChangeView.as_view(), name='password-change'),
    # url(r'^password-reset/$', PasswordResetView.as_view(), name='password-reset'),
    # url(r'^password-reset-done/$', PasswordResetDoneView.as_view(), name='password-reset-done'),
    # url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$',
    #     PasswordResetConfirmView.as_view(),
    #     name='password-reset-confirm'),
]

mysite/urls.py
from django.conf.urls import include, url
from mysite.views import *
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns=[
    url(r'^$',HomePage.as_view(), name='home'),
    url(r'^sendcontactmail/$', HomePage().send_contact_mail, name='sendcontactmail'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
]

dashboard/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from authtools import forms as authtoolsforms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Field
# from dashboard.models import CreateTest
from django.core.urlresolvers import reverse

# class FileField(Field):
#     template = 'bootstrap/layout/file_field.html'


class CreateTestForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(CreateTestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['email'].widget.input_type = "text"  # ugly hack

        self.helper.layout = Layout(
            # FileField('main_image',placeholder="Enter Email", autofocus=""),
            # Field('test_image', placeholder="Enter Email", autofocus=""),
            Field('email', placeholder="Enter email", autofocus="", css_class="form-control"),

            Submit('launch', 'Launch',css_class="btn btn-lg btn-primary btn-block"),
        )
    #
    # class Meta:
    #     model = CreateTest

dashboard/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
import requests,subprocess
from rest_framework.views import APIView
from rest_framework.response import Response
import re,boto3,threading
from dashboard import forms
# USERNAME_PASSWORD = "admin:admin@123"

"""
Getting Started View to create a new application
@input application_name,category,platform,time_zone
@output project_token
"""
# User =get_user_model()

def async(function):
    def async_decorator(*args, **kwargs):
        try:
            t = threading.Thread(target=function,args=args,kwargs = kwargs)
            t.setDaemon(False)
            t.start()
        except:
            return {"status": "Unsuccesfull"}
    return async_decorator


class VisionView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/vision_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['api_host'] = settings.API_HOSTNAME
        return super(VisionView, self).get(request, *args, **kwargs)


class UploadFile(APIView):
    def post(self,request,media_id=''):
        if request.method != 'POST':
            return Response({"response":'Only POST requests are allowed'})
        file = request.FILES['filetoupload']
        file.name = filter(lambda x: str.isalnum(x) or "." == x or "-" == x or  "_" == x, file.name.encode())
        with open('static/media/%s' % str(media_id)+"_"+file.name,'wb+') as dest:
            for chunk in file.chunks():
                dest.write(chunk)
        print file.name.replace('(','\(').replace(')',"\)")
        png = "".join(file.name.split(".")[:-1])
        subprocess.call("ffmpeg -i static/media/"+str(media_id)+"_"+re.escape(file.name)+" -vcodec  png -ss 1 -vframes 1 -an -f  rawvideo static/media/"+str(media_id)+"_"+png+".png",shell=True)
        return Response({"response":'File uploaded'})
            



class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/home_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['api_host'] = settings.API_HOSTNAME
        return super(HomeView, self).get(request, *args, **kwargs)


class DashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/dashboard_view.html"

    def get(self, request, project_id='', media_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        kwargs['media_id'] = media_id
        return super(DashboardView, self).get(request, *args, **kwargs)


class CreateTestView(LoginRequiredMixin, APIView, generic.TemplateView):
    template_name = "dashboard/create_test_view.html"
    http_method_names = ['get', 'post']
    form_class = forms.CreateTestForm

    def get(self, request, project_id='', media_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        kwargs['media_id'] = media_id
        #form=self.form_class,
        return super(CreateTestView, self).get(request, *args, **kwargs)

    def post(self, request, project_id='', media_id=''):

        return redirect("dashboard:project_overview")


class TestDetails(LoginRequiredMixin, APIView, generic.TemplateView):
    template_name = "dashboard/test_details.html"
    http_method_names = ['get', 'post']
    def get(self, request, project_id='', media_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        kwargs['media_id'] = media_id
        return super(TestDetails, self).get(request, *args, **kwargs)

    def post(self, request, project_id='', media_id=''):
        return redirect("dashboard:project_overview")



class ProjectView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/project_view.html"

    def get(self, request, project_id='',*args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        return super(ProjectView, self).get(request, *args, **kwargs)


class MediaView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/media_overview.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        return super(MediaView, self).get(request, *args, **kwargs)

    def post(self):
        return redirect("dashboard")


class AddMediaView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/add_media.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(AddMediaView, self).get(request, *args, **kwargs)

class MediaOverview(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/media_overview_list.html"

    def get(self, request, *args, **kwargs):
        kwargs["project_id"] = kwargs["project_id"]
        kwargs['user'] = self.request.user
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(MediaOverview, self).get(request, *args, **kwargs)


class MediaReportsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/media_overview_report.html"

    def get(self, request, *args, **kwargs):
        kwargs["project_id"] = kwargs["project_id"]
        kwargs["media_id"] = kwargs["media_id"]
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(MediaReportsView, self).get(request, *args, **kwargs)


class ReportsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/reports_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        return super(ReportsView, self).get(request, *args, **kwargs)


class CompareReportsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/compare_reports_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        return super(CompareReportsView, self).get(request, *args, **kwargs)


class SettingsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/settings.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(SettingsView, self).get(request, *args, **kwargs)

class ManageProjectView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/manage_projects.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        return super(ManageProjectView, self).get(request, *args, **kwargs)

class AddProjectView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/add_project.html"

    def get(self, request,project_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        return super(AddProjectView, self).get(request, *args, **kwargs)

class AddTestView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/add_test.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = request.GET.get('project_id')
        return super(AddTestView, self).get(request, *args, **kwargs)


class EditTestView(LoginRequiredMixin, APIView, generic.TemplateView):
    template_name = "dashboard/edit_test.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['media_id'] = request.GET.get('media_id')
        kwargs['project_id'] = request.GET.get('project_id')
        kwargs['activity_type'] = request.GET.get('activity_type')
        return super(EditTestView, self).get(request, *args, **kwargs)


class TrackTestView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/test_details.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs["project_id"] = kwargs["project_id"]
        kwargs["media_id"] = kwargs["media_id"]
        return super(TrackTestView, self).get(request, *args, **kwargs)


class S3FileUploadAPI(APIView):

    def __init__(self):
        self.s3 = boto3.resource('s3')
        self.client = boto3.client('s3')

    def common_read(self,bucket,prefix,filename):
        try :
            bucket = self.s3.Bucket(bucket)
            prefix = prefix.strip().rstrip('/')

delegate/views.py
from __future__ import unicode_literals
from django.views import generic
from django.conf import settings
# settings.LOGIN_URL='/tester/login/'
# settings.LOGIN_REDIRECT_URL='/tester/home_view/'
# User = get_user_model()


class SignUpView(generic.TemplateView):
    template_name = "delegate/signup.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(SignUpView, self).get(self, *args, **kwargs)

templates/delegate/auth_base.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block navbar %}
{% endblock %}


{% block container %}
<div class="container form-box">
  <div class="text-center">
    <h2>{% block form_heading %}{% endblock %}</h2>
  </div>
  {% block form %}
  {% endblock %}
</div>

{% endblock container %}
{% block js %}
{% endblock %}

templates/delegate/dashboard_view.html
{% extends "dashboard/template.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block navlink %}
    <li><a href="{% url 'dashboard:home_view' %}">Home</a></li>
{% endblock %}
{% block css %}
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" type="text/css" rel="stylesheet">
    <link href="{% static 'css/rickshaw.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/dashboard_graph_view.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/dashboard_responsive.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block container %}
    <input type="hidden" id="user_id" value="{{ user.id }}">
    <!-- Left Section -->
    <div class="col-md-3 left_pane">
        <div class="row-fluid">
            <label for="project_dd">Select Project:</label>
            <select class="project_list btn btn-default dropdown-toggle dropdown_btn" id="project_dd"></select>
        </div>
        <br>
        <div class="row-fluid">
            <label for="media_dd">Select Media:</label>
            <select class="media_list btn btn-default dropdown-toggle dropdown_btn" id="media_dd"></select>
        </div>
        <br>
        <div class="row-fluid">
            <div class="image_wrapper"></div>
        </div>
        <br>
        <div class="row-fluid research_parameters">
            <h4>Research Parameters</h4>
            <table class="table table-bordered">
                <tr><td class="selected_param" val="attention">Attention</td>
                    <td val="meditation">Meditation</td></tr>
                <tr><td val="BP">Band Power</td><td val="ET">eTensity</td></tr>
                <tr><td val="YF">Familiarity</td><td val="Blink">Eye Blink</td></tr>
                <tr><td val="YY">YinYang</td><td val="AL">Alertness</td></tr>
                <tr><td val="AP">Appreciation</td><td val="ME">Mental Effort</td></tr>
                <tr><td val="CR">Creativity</td><td val="CP">Preparedness</td></tr>
            </table>
        </div>

        <div class="row-fluid metrics">
            <h4>Metrics</h4>
            <table class="table table-bordered">
                <tr><td class="selected_param" val="avg">Average</td><td val="var">Varience</td></tr>
            </table>
        </div>
        <div class="row-fluid gender">
            <h4>Gender</h4>
            <table class="table table-bordered">
                <tr><td class="selected_param" val="all">All</td><td class="compare" val="versus">Versus</td></tr>
                <tr><td val="male">Male</td><td val="female">Female</td></tr>
            </table>
        </div>

        <div class="row-fluid age">
            <h4>Age</h4>
            <table class="table table-bordered">
                <tr><td class="selected_param" val="all">All</td><td class="compare" val="versus">Versus</td></tr>
                <tr><td val="below">Below 29</td><td val="average">29-50</td></tr>
                <tr><td val="above">Above 50</td></tr>
            </table>
        </div>
    </div>
    <!-- Right Section -->
    <div class="col-md-9 right_pane ">
        <div class="row-fluid">
            <div class="benchmark_row">
                <span class="left_heading">Benchmark</span>
                <div class="right_float dropdown">
                    <button class="btn btn-default dropdown-toggle dropdown_btn" type="button" data-toggle="dropdown">Category
                        <span class="pull-right  caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#">Category 1</a></li>
                        <li><a href="#">Category 2</a></li>
                        <li><a href="#">Category 3</a></li>
                    </ul>
                </div>

                <div class="right_float dropdown">
                    <button class="btn btn-default dropdown-toggle dropdown_btn" type="button" data-toggle="dropdown">
                        Gender<span class="pull-right  caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#">Male</a></li>
                        <li><a href="#">Female</a></li>
                    </ul>
                </div>
                <div class="right_float dropdown">
                    <button class="btn btn-default dropdown-toggle dropdown_btn" type="button" data-toggle="dropdown">
                        Age<span class="pull-right  caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#">Young</a></li>
                        <li><a href="#">Teen</a></li>
                        <li><a href="#">Old</a></li>
                    </ul>
                </div>
            </div>
            <div class="smoothing_row">
                <span class="left_smooth">Smoothing</span>
                <div id="smoother"></div>
                <span class="reset_btn">Reset</span>
                <span class="right_heading">Scaling</span>
                <div id="preview"></div>
                <span class="graph_filters box_text">Graphs<span class="caret"></span></span>
            </div>
            <div class="export_div">Export
                <span class="pull-right caret"></span>
            </div>
            <div class="graph_filter_view">
                <form id="side_panel">
                    <div id="interpolation_form">
                        <label for="cardinal" class="selected_param">
                            <input type="radio" name="interpolation" id="cardinal" value="cardinal" checked>
                            <span>cardinal</span>
                        </label>
                        <label for="linear">
                            <input type="radio" name="interpolation" id="linear" value="linear">
                            <span>linear</span>
                        </label>
                        <label for="step">
                            <input type="radio" name="interpolation" id="step" value="step-after">
                            <span>step</span>
                        </label>
                    </div>
                    <div id="renderer_form" class="toggler">
                        <label for="area">
                            <input type="radio" name="renderer" id="area" value="area">
                            <span>area</span></label>
                        <label for="bar">
                            <input type="radio" name="renderer" id="bar" value="bar">
                            <span>bar</span></label>
                        <label for="line" class="selected_param">
                            <input type="radio" name="renderer" id="line" value="line" checked>
                            <span>line</span></label>
                        <label for="scatter">
                            <input type="radio" name="renderer" id="scatter" value="scatterplot">
                            <span>scatter</span></label>
                    </div>
                    <div id="offset_form">
                        <label for="stack">
                            <input type="radio" name="offset" id="stack" value="zero" checked>
                            <span>stack</span>
                        </label>
                        <label for="stream">
                            <input type="radio" name="offset" id="stream" value="wiggle">
                            <span>stream</span>
                        </label>
                        <label for="pct">
                            <input type="radio" name="offset" id="pct" value="expand">
                            <span>pct</span>
                        </label>
                        <label for="value" class="selected_param">
                            <input type="radio" name="offset" id="value" value="value">
                            <span>value</span>
                        </label>
                    </div>
                    <div id="legend"></div>
                </form>
            </div>
        </div>

        <br>

        <div class="row-fluid" id="chart_wrapper">
            <div class="chart_block_row">
                <div class="img_section">
                    <img class="thumbnail_image" src="{% static 'img/video_link.jpg' %}">
                    <img class="last_one" src="{% static 'img/video_link.jpg' %}">
                </div>
                <div id="content">

                    <div id="chart_container">
                        <div id="y_axis"></div>
                        <div id="chart"></div>
                        <div id="x_axis"></div>
                        <div id="timeline"></div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row-fluid">
            <div class="data_table">
                <table class="table right_table">
                    <thead>
                    <tr>
                        <td><h5>No Table Data Exist</h5></td>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


        <input type="hidden" id="api_url" value="{{ api_url }}">
        <input type="hidden" id="host_url" value="{{ host_url }}">

{% endblock %}


{% block js %}
    {#    <script src="{% static 'js/jquery-ui.js' %}"></script>#}
    {#    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>#}
    <script src="{% static 'js/jquery-ui-update.js' %}"></script>
    <script src="{% static 'js/d3.min.js' %}"></script>
    <script src="{% static 'js/d3.layout.min.js' %}"></script>
    <script src="{% static 'js/rickshaw.min.js' %}"></script>
    <script src="{% static 'js/extensions.js' %}"></script>
    <script src="{% static 'js/common_functions.js' %}"></script>
    <script src="{% static 'js/render_graph.js' %}"></script>
    <script src="{% static 'js/dashboard_view.js' %}"></script>
{% endblock %}

templates/delegate/home_view.html
{% extends "profile_base.html" %}
{% load staticfiles %}
{% block navlink %}
        <li><a href="{% url 'tester:dashboard_view' %}">Dashboard</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
                {{ user.username |truncatechars:20 }}Tester
                <span class="caret"></span>
            </a>

            <ul class="dropdown-menu" role="menu">
                <li><a class="text-warning text-capitalize" href="{% url 'profiles:show_self' %}">Profile</a>
                </li>
                <li><a class="text-warning" href="{% url 'tester:logout' %}">Logout</a></li>
            </ul>
        </li>
{% endblock %}
{% block splash %}
    <link href="{% static 'css/rickshaw.css' %}" rel="stylesheet" type="text/css">

    <style type="text/css">
        body{
            font-family: pnaltbold,sans-serif;
        }
        .row-fluid {
            display:  flex;
            flex-wrap: wrap;
        }
        .row-fluid > [class*='col-'] {
            display: flex;
            flex-direction: column;
            padding: 5px;
        }
        .link_text img{
            width: 80px;
            height: 80px;
            margin: 18px;
        }
        .link_text{
            background-color: rgb(61, 158, 153);
            height:150px;
            font-size: 16px;
            margin-top: 10px;
            text-align: center;
            color: #fff;
        }
        .link_text:hover,.link_text:focus{
{#            transition: [transition-property] [transition-duration] [transition-timing-function] [transition-delay]; #}
            background-color: rgb(255, 181, 85);
            transition: background-color 0.3s ease;
            color: rgb(255,255,255);
            cursor: pointer;
            text-decoration: none;
        }.paddingtop{
             margin-top: 30px;
             margin-left: 15px;
         }
        .center_align{
            padding-top: 60px;
        }
    </style>
    <link href="{% static 'css/home_responsive.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block container %}
    <div class="container-fluid paddingtop">
        <div class="row-fluid">
            <div class="col-md-1.5"></div>
            <div class="col-md-1.5 ">
                <a class="link_text" href="{% url 'dashboard:project_overview' %}">
                    <img src="{% static 'img/login_icons/projects.png' %}">
                    <div class="text_block">
                        Project View
                    </div>
                </a>
            </div>
            <div class="col-md-1.5 ">
                <a class="link_text" href="{% url 'dashboard:media_overview' %}">
                    <img src="{% static 'img/login_icons/media.png' %}">
                    <div class="text_block">Media View</div>
                </a>
            </div>
            <div class="col-md-1.5 ">
                <a class="link_text" href="{% url 'dashboard:view_reports' %}">
                    <img src="{% static 'img/login_icons/reports.png' %}">
                    <div class="text_block">Reports and Charts</div>
                </a>
            </div>
            <div class="col-md-1.5 ">
                <a class="link_text" href="{% url 'dashboard:compare_reports' %}">
                    <img src="{% static 'img/login_icons/compare.png' %}">
                    <div class="text_block">Compare</div>
                </a>
            </div>
            <div class="col-md-1.5"></div>
            <div class="col-md-1.5"></div>
        </div>
    </div>


{% endblock %}

templates/delegate/password-change.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}
<!-- Benefits of the Django application -->
{% block container %}
<style type="text/css">
.top_margin{
    margin-top: 70px !important;
}
.btn-inline:nth-of-type(2){
    margin-left: 60px;
}
</style>
<div class="col-md-offset-4 col-md-4 top_margin">
<h1>Password Change</h1>

{% block form %}
  {% crispy form %}
{% endblock form %}
</div>
{% endblock %}