accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^schedule-demo-success/$', views.ScheduleDemoSuccessView.as_view(), name='schedule-demo-success'),

    # url(r'^activate/(?P<key>.+)$', views.SignUpView().activate_user,name='activate'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(), name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(), name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

brainvita_frontend/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import accounts.urls
import profiles.urls
import dashboard.urls
import mysite.urls
import delegate.urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profiles.urls, namespace='profiles')),
    url(r'^users/', include(dashboard.urls, namespace='dashboard')),
    url(r'^tester/', include(delegate.urls, namespace='tester')),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(mysite.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import include, url
from mysite.views import *
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns=[
    url(r'^$',HomePage.as_view(), name='home'),
    url(r'^sendcontactmail/$', HomePage().send_contact_mail, name='sendcontactmail'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(label="Remember Me?", required=False, initial=False)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = True
        self.fields["username"].widget.input_type = "text"  # ugly hack
        self.fields['username'].label = ""
        self.fields['password'].label = ""
        self.fields['remember_me'].label = "Remember Me"


        self.helper.layout = Layout(
            Field('username', placeholder="Email", autofocus=""),
            Field('password', placeholder="Password"),
            HTML('<a href="{}">Forgot Password?</a>'.format(
                reverse("accounts:password-reset"))),
            Field('remember_me',css_class="check"),

            Submit('sign_in', 'Log in',
                   css_class="login"),
            )


class SignupForm(authtoolsforms.UserCreationForm):
    phone_number_errors = {
    'required': 'This field is required',
    'invalid': 'Enter valid phone number, min length 5 and max length 15.'
    }
    phone_number = forms.RegexField(regex=r'^\+?\d{5,15}$', error_messages = phone_number_errors)
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["email"].widget.input_type = "text"  # ugly hack

        self.helper.layout = Layout(
            Field('username', placeholder="Enter Full Name", autofocus=""),
            Field('email', placeholder="Enter Email"),
            Field('password1', placeholder="Enter Password"),
            Field('password2', placeholder="Re-enter Password"),
            Field('phone_number', placeholder="Enter Phone Number"),
            Submit('sign_up', 'Sign up', css_class="btn btn-lg btn-primary btn-block"),
            )

    def save(self, is_active=False):
        """
        Saving the user instance with status as inactive
        """
        user = super(SignupForm, self).save(commit=False)
        user.is_active=is_active
        user.save()
        return user


class PasswordChangeForm(authforms.PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # This form will be displayed for change password button
        # cancel button is included for going back url.
        self.helper.layout = Layout(
            Field('old_password', placeholder="Enter old password",autofocus=""),
            Field('new_password1', placeholder="Enter new password"),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn btn-lg btn-success btn-inline"),
            Button('cancel', 'Cancel',onclick='history.go(-1);',css_class="btn btn-lg btn-danger btn-inline"),
            )


class PasswordResetForm(authtoolsforms.FriendlyPasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["email"].widget.input_type = "text"  # ugly hack

        self.helper.layout = Layout(
            Field('email', placeholder="Enter email",
                  autofocus=""),
            Submit('pass_reset', 'Reset Password', css_class="login"),
            )


class SetPasswordForm(authforms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('new_password1', placeholder="Enter new password",
                  autofocus=""),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn btn-lg btn-primary btn-block"),
            )

accounts/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from django.contrib.auth import logout
from braces import views as bracesviews
from django.conf import settings
from . import forms
from profiles.models import Profile
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect

from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from utils import send_activatation_email
from utils import send_after_activate_mail
from utils import generate_activation_key

User = get_user_model()


class LoginView(bracesviews.AnonymousRequiredMixin,
                authviews.LoginView):
    form_class = forms.LoginForm
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        redirect = super(LoginView, self).form_valid(form)
        remember_me = form.cleaned_data.get('remember_me')
        if remember_me is True:
            ONE_MONTH = 30 * 24 * 60 * 60
            expiry = getattr(settings, "KEEP_LOGGED_DURATION", ONE_MONTH)
            self.request.session.set_expiry(expiry)
        return redirect


class LogoutView(authviews.LogoutView):
    url = reverse_lazy('accounts:login')



class SignUpView(generic.TemplateView):
    template_name = "accounts/signup.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(SignUpView, self).get(self, *args, **kwargs)

class ScheduleDemoSuccessView(generic.TemplateView):
    template_name = "accounts/scheduledemo_success.html"

class PasswordChangeView(authviews.PasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = 'accounts/password-change.html'
    success_url = reverse_lazy("accounts:login")

    def form_valid(self, form):
        form.save()
        logout(self.request)
        messages.success(self.request,
                         "Your password was changed, "
                         "hence you have been logged out. Please relogin")
        return super(PasswordChangeView, self).form_valid(form)


class PasswordResetView(authviews.PasswordResetView):
    form_class = forms.PasswordResetForm
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'accounts/emails/password-reset-email.html'


class PasswordResetDoneView(authviews.PasswordResetDoneView):
    template_name = 'accounts/password-reset-done.html'


class PasswordResetConfirmView(authviews.PasswordResetConfirmAndLoginView):
    template_name = 'accounts/password-reset-confirm.html'
    form_class = forms.SetPasswordForm

templates/accounts/activate_email.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activate Email</title>
</head>
<body>
<table style="background-color:#1B3949" width="100%" cellpadding="20">
    <tbody><tr><td style="text-align: center"><img style="width: 140px;height: 70px;" src="{% static 'img/affectlab_logo.png' %}" /></td></tr>
    </tbody></table>
<div style="font-size: 16px;font-family: 'Helvetica Neue Light',Helvetica,sans-serif;color: #222;line-height: 150%;">
    <h2 style="font-size:20px;font-family:'Helvetica Neue';color: #3d70b2;">Hi {{ name }},</h2>
Thank you for signing up for Affect Lab! Your 30-day trial is free, with no credit card required.
<p style="background-color:#3d70b2;width:180px;height:50px;text-align:center"><b>
<a href='{{protocol}}{{ host }}/activate/{{activation_key}}' target="_blank" style="font-size:16px;line-height: 150%;color:#ffffff;display:table-cell;vertical-align:middle;padding:12px;text-decoration:none" >Confirm Account</a>
</b></p>
By confirming your account, you accept the Affect Lab <a href="{{protocol}}{{ host }}/terms" style="color: #3d70b2;text-decoration: underline;">Terms of Use</a>.
If you have problems logging in, go to Affect Lab <a style="color: #3d70b2;text-decoration: underline;" href="{{protocol}}{{ host }}/contact">contact us</a>. We look forward to seeing what you create!
<br><br>Regards,<br><br>
Affect Lab Team
</div>
</body>
</html>

templates/accounts/auth_base.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block navbar %}
{% endblock %}


{% block container %}
    <style>
        .gray-bg{
            background-color: #fff !important;
        }
    </style>
<div class="container form-box">
  <div class="text-center">
    <h2>{% block form_heading %}{% endblock %}</h2>
  </div>
  {% block form %}
  {% endblock %}
</div>

{% endblock container %}

templates/accounts/login.html
{% extends "accounts/auth_base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}Neuro sensum | Login {% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">  <!-- singular -->
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block form %}
<style>
        html , body{
            height: 0px !important;
            min-width: 0px !important;
            background: #808083 !important;
        }
        /*.container{
            background: #dadada;
            margin-top:5%; 
            vertical-align: middle;
        }*/
    </style>
    <div class="text-center col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 col-sm-offset-4 col-sm-4 col-sm-offset-4 col-xs-12">
        <div style="">
            <a href="/">
                <h1 class="logo-name">
                    <img src="{% static 'ico/favicon.png' %}" class="img-responsive m-t-xl"></h1>
            </a>
        </div>
        <br>
        <h3 class="m-t">Login to Neuro Sensum</h3>
        {% crispy form %}
        <p class="entropik-t">
            <small>Neuro sensum &copy; 2017</small>
        </p>
    </div>
{% endblock form %}

templates/accounts/login_new.html
{% extends "accounts/auth_base.html" %}
{% load staticfiles %}
{% block navbar %}
    <style type="text/css">
    label{
        text-align: left;
        display: block;
    }
    </style>
{% endblock %}



{% block form %}
    <div class="middle-box text-center loginscreen animated fadeInDown">
    <div style="">
        <a href="/"><h1 class="logo-name"><img src="{% static 'ico/favicon.png' %}" class="img-responsive"></h1></a>
    </div>
    <h3>Login to Neuro Sensum</h3>
        <form name="login_form" method="POST">
            {% csrf_token %}
            <label for="username">Username<span class="asteriskField">*</span>:</label>
            <input type="text" required id="username" name="username" placeholder="Enter Username" class="form-control">
            <span class="username_status"></span>
            <label for="new_password">Enter Password<span class="asteriskField">*</span>:</label>
            <input type="password" required id="password" name="password" placeholder="Enter Password" class="form-control"><br>
            <input type="submit" class="btn btn-sm btn-primary btn-block" value="Log in">
            <input type="hidden" id="api_host" value="{{ api_url }}">
            <p class="text-muted text-center"><small>Do not have an account?</small></p>
            <a class="btn btn-sm btn-white btn-block" href="{% url 'accounts:signup' %}">Create an account</a>
        </form>
        <p class="m-t"> <small>Entropik Technologies Pvt. Ltd. &copy; 2017</small> </p>
    </div>
{% endblock form %}
{% block scripts %}
    <script src="{% static 'js/common_functions.js' %}"></script>
    <script type="text/javascript">
    $(function () {
        var api_host = $("#api_host").val();
       var admin_login_form = $("form[name='login_form']");
       admin_login_form.on('submit',function (event) {
           event.preventDefault();
            var signup_url= api_host +"dashboard/login/";
            var ajax_data = {
                "username":$("input[name='username']").val(),
                "password":$("input[name='password']").val()
            };
            debugger;
           var get_signup_status = call_ajax("POST",signup_url,ajax_data);
           debugger;
           if(get_signup_status.status == "success")
           {
               window.location = "/users/home/";
           }
           else{
               $(".error_message").text(get_signup_status.status);
               return false;
           }
       });
    });
    </script>
{% endblock %}
{# class LoginView(generic.TemplateView):#}
{##     template_name = "accounts/login.html"#}
{##     http_method_names = ['get']#}
{###}
{##     def get(self, request, *args, **kwargs):#}
{##         kwargs['api_url'] = settings.API_ENDPOINT#}
{##         return super(LoginView, self).get(self, *args, **kwargs)#}

templates/accounts/password-change.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}
<!-- Benefits of the Django application -->
{% block container %}
<style type="text/css">
.top_margin{
    margin-top: 70px !important;
}
.btn-inline:nth-of-type(2){
    margin-left: 60px;
}
</style>
<div class="col-md-offset-4 col-md-4 top_margin">
<h1>Password Change</h1>

{% block form %}
  {% crispy form %}
{% endblock form %}
</div>
{% endblock %}

templates/accounts/password-reset-confirm.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
  {% crispy form %}
{% endblock form %}

templates/accounts/password-reset-done.html
{% extends "accounts/auth_base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block form %}
    <div class="middle-box text-center loginscreen animated fadeInDown">
    <div style="margin-bottom: 75px;">
        <h1 class="logo-name"><img src="{% static 'ico/favicon.png' %}" class="img-responsive"></h1>
    </div>
        <h3>Password Reset Done</h3>
        <p>
            Please check your mail. You would have received a password reset mail from us.
        </p>
        <p class="m-t"> <small>Entropik Technologies Pvt. Ltd. &copy; 2017</small> </p>
    </div>
    </div>

{% endblock form %}

templates/accounts/password-reset.html
{% extends "accounts/auth_base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block form %}
    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div style="margin-bottom: 75px;margin-left: 78px;">
            <h1 class="logo-name"><img src="{% static 'site/img/affect_lab_logo.png' %}" class="img-responsive"></h1>
        </div>
        <h3 class="password">Password Reset</h3>
  {% crispy form %}
    <p class="m-t"> <small>Entropik Technologies Pvt. Ltd. &copy; 2017</small> </p>
    </div>
{% endblock form %}

templates/accounts/scheduledemo_success.html
{% extends "accounts/auth_base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title %}Neuro Sensum - Schedule Demo Success{% endblock %}



{% block container %}

    <div class="text-center col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6 col-sm-offset-3 col-xs-12" style="margin-top: 100px;">
        <div style="">
            <a href="/">
                <h1 class="logo-name">
                    <img src="{% static 'site/img/affect_lab_logo.png' %}" class="img-responsive m-t-xl"></h1>
            </a>
        </div><br>
        <h3 >THANK YOU FOR REACHING OUT!
        </h3>
        <br>
        <h6 style="font-size: 16px">One of us from Affect Lab is looking into your requirements right now and will be contacting you soon to schedule a demo. </h6>
        <h6 style="font-size: 16px">But while you’re waiting (promise, not too long), see what we’re up to on social!
        </h6>

        <div class="row" style="margin-top: 50px;">
            <div class="col-md-12 col-sm-12 footer-social text-center sm-text-center">
                <!-- social media link -->
                <a target="_blank" href="https://www.facebook.com/entropiktech"><i class="fa fa-facebook"></i></a>
                <a target="_blank" href="https://twitter.com/entropiktech"><i class="fa fa-twitter"></i></a>
                <a target="_blank" href="https://www.linkedin.com/company/7795723"><i class="fa fa-linkedin"></i></a>
                <!-- end social media link -->
            </div>
        </div>
    </div>
{% endblock container %}

templates/accounts/signup_new.html
<!DOCTYPE html>{% load staticfiles %}
<html>
<head>
    <meta charset="UTF-8">
</head>
<body style="margin:0">

  <div style="width: 100%;min-width: 702px;background-color: #e8ecf0;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 12px;font-weight: 200;line-height:20px;padding: 40px 0 100px 0;">
    <div style="width:702px;margin:0 auto">
      <img src="{% static 'site/img/signup_mail/mail.png' %}"/>
     <div style="border-bottom:1px solid #e6eff8;padding:50px 70px 65px 80px;background: rgba(228, 182, 182, 0.24);">
      <div>
        <h1 style="color:#4b5660;text-align:center;font-size:24px;font-weight:700;line-height:24px;margin-bottom:30px">INSTALL ONE OF OUR SDKs</h1>
        <table>
          <tbody>
           <tr>
            <td style="width: 110px;text-align:center;height:100px;padding-right: 58px;">
              <a href="#" style="text-decoration:none;color:#757d86;">
                <img src="{% static 'site/img/signup_mail/icon_ios.png' %}" style="height:100px;margin-bottom:20px;" >
                ios
              </a>
            </td>
            <td style="width:110px;text-align:center;height:100px;padding-left:45px;">
              <a href="#" style="text-decoration:none;color:#757d86;">
                <img src="{% static 'site/img/signup_mail/icon_android.png' %}" style="height:100px;margin-bottom:30px"  >
                Android
              </a>
            </td>
            <td style="width:110px;text-align:center;height:100px;padding-left: 68px;">
              <a href="#" style="text-decoration:none;color:#757d86;">
                <img src="{% static 'site/img/signup_mail/icon_java.png' %}" style="height:100px;margin-bottom:30px"  >Javascript
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
    <div style="text-align:left;padding:82px 0 53px 41px;;color:#4b5660;font-size:19px;font-weight:500;background-color:#fff;">
      Have a question? Email our support team at <a href="mailto:support@chromo.io" style="border:0;font-weight:500;font-size:19px;color:#a5b1c1;text-decoration:none" target="_blank">support@chromo.io</a>&nbsp;or talk to us on our community forum.
    </div>
  </div>
</div>
</body>
</html>