brainvita_frontend/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import accounts.urls
import profiles.urls
import dashboard.urls
import mysite.urls
import delegate.urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profiles.urls, namespace='profiles')),
    url(r'^users/', include(dashboard.urls, namespace='dashboard')),
    url(r'^tester/', include(delegate.urls, namespace='tester')),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(mysite.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import include, url
from mysite.views import *
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns=[
    url(r'^$',HomePage.as_view(), name='home'),
    url(r'^sendcontactmail/$', HomePage().send_contact_mail, name='sendcontactmail'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
]

profiles/urls.py
from django.conf.urls import url
from profiles import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^myaccount$', views.ShowAccount.as_view(), name='show_account'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

profiles/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.conf import settings


class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True)
    # phone_number = models.CharField(max_length=20)
    # slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    mobile = models.CharField(null= True,max_length=30)
    work_number = models.CharField(null= True,max_length=30)
    designation = models.CharField(null = True,max_length=100)
    company_name = models.CharField(null=True, max_length=100)
    picture = models.ImageField('Profile picture',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField("Short Bio", max_length=200, blank=True, null=True)
    # email_verified = models.BooleanField("Email verified", default=False)
    # activation_key = models.CharField(max_length=40)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Profile(BaseProfile):
    class Meta:
        app_label = 'profiles'

    def __str__(self):
        return "{}'s profile".format(self.user)

profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from . import models
from django.contrib.auth.models import User

# User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('username'),
            )

    class Meta:
        model = User
        fields = ('username',)


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('picture'),
            Field('bio'),
            Submit('update', 'Update', css_class="btn btn-success btn-lg"),
            )

    class Meta:
        model = models.Profile
        fields = ['picture', 'bio']

profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from braces.views import LoginRequiredMixin
from . import models
from django.conf import settings
from pytz import timezone
from profiles import forms

class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['user'] = self.request.user
        kwargs['api_host'] = settings.API_HOSTNAME
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True

            # converting the utc time to gmt timezone
            last_login = user.last_login.astimezone(timezone("Asia/Kolkata"))
            date_joined = user.date_joined.astimezone(timezone("Asia/Kolkata"))
            # convert time to string format
            user.last_login = last_login.strftime("%b. %d, %Y, %I:%M %P")
            user.date_joined = date_joined.strftime("%b. %d, %Y, %I:%M %P")
        kwargs["show_user"] = user
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                                    "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")


class ShowAccount(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_account.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        project_token = request.user.application.project_token
        api_url = settings.API_ENDPOINT
        kwargs["show_user"] = user
        return super(ShowAccount, self).get(request, project_token=project_token, api_url=api_url)

templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">Edit Profile</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Personal info</h3>
      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}
          <a class="btn btn-info btn-lg btn-inline" href="{% url 'accounts:password-change' %}">Change Password</a>
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>
{% endblock %}

templates/profiles/show_account.html
{% extends "profile_base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }}Account{% endblock %}
{% block sidebar %}

<style type="text/css">

	#myProgress {
    position: relative;
    width: 100%;
    height: 30px;
    border:1px solid #1487bd;
}
#myBar {
    position: absolute;
    width: 0;
    height: 100%;
    background-color: #1487bd;
}
.row{
	height: 40px;
}

.my_btn{
    background-color: #1487bd;
    border:0;
    height:30px;
    color:#fff;
    float: right;
}
body{
    height:90%;
}
.bold_text{
    font-family:pnaltbold;
}
.center_text{
    text-align: center;
}
.right_text{
    float: right;
}
.body_text span,.body_text label{
    font-size: 16px;
}
#count_value{
    color:rgba(0,122,196,1);
}

</style>
<ul class="sidebar-nav">
    {% comment %}<div class="sidebar_top_text">Documentation</div>
    <li>
        {#  {% url 'dashboard:posture_pattern' %}{% url 'dashboard:gettingstarted' %}#}
        <a href="{% url 'profiles:featured_guide' %}"><span>Featured guide</span></a>
    </li>
    <li>
        <a href="{% url 'profiles:api_usage_guide' %}"><span>API Usage guide</span></a>
    </li>
    <li>
        <a href="{% url 'profiles:faq' %}"><span>FAQ</span></a>
    </li>
    <hr class="black_border">{% endcomment %}
</ul>
{% endblock sidebar %}
{% block container %}

<div class="body_text">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h2>Bill Plan</h2>
        </div>
    </div>
</div>
<div class="container-fluid">
  <div class="row">
  	<div class="col-md-12">
  		<label class="bold_text">Current Monthly Usage</label>
  	</div>
  	<div class="col-md-4">
  		<div id="myProgress">
	  <div id="myBar"></div>
	</div>
  	</div>
  	<div class="col-md-4 center_text">
        <span class="bold_text"><span id="count_value"></span> of 10000</span>  <label>monthly Users active</label>
  	</div>
  	<div class="col-md-2">
  		<input class="my_btn"  type="button" value="Upgrade Now">
  	</div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
  	<div class="col-md-12">
  		<h2>Project Details</h2>
  	</div>
      <div class="clearfix"></div>
  </div>
</div>
    <br>
<div class="container-fluid">
  <div class="row">
  	<div class="col-md-2">
  		<span>Usage Tier<span class="right_text">:</span></span>
  	</div>
  	<div class="col-md-10">
  		<label class="bold_text">Free Tier</label>
  	</div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container-fluid">
  <div class="row ">
  	<div class="col-md-2">
  		<span>Project Token<span class="right_text">:</span></span>
  	</div>
  	<div class="col-md-10">
  		<label class="bold_text">{{project_token}}</label>
        <input type="hidden" id="project_token" value="{{ project_token }}">
        <input type="hidden" id="api_url" value="{{ api_url }}">
  	</div>
  </div>
</div>
</div>

{% endblock %}

{% block scripts %}
{#    this code comes after the footer section #}
<script type="text/javascript">
$(function () {
    {# taking the token and urls    #}
    var  PROJECT_TOKEN = $('#project_token').val();
    var API_HOSTNAME =$('#api_url').val();
    var url = 'getactiveusers';
    {# for passing the end date in the format of yyyy-dd-mm #}
    var current_date = new Date().toISOString();
    var end_date= current_date.slice(0,4) +"-"+current_date.slice(8,10)+"-"+current_date.slice(5,7);

    filter_json={'end_date':end_date};

        try {
            $.ajax({
                type: "POST",
                url: API_HOSTNAME + url + "/" + PROJECT_TOKEN + "/",
                dataType: 'json',
                beforeSend: function (xhr) {
                    var user = "apiuser";// your actual username
                    var pass = "entropik123";// your actual password
                    var token = user.concat(":", pass);
                    xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
                    xhr.setRequestHeader('Authorization', ("Basic ".concat(btoa(token))));
                },
                data: JSON.stringify(filter_json),
                async: false,
                success: function (data) {
                    var count=0;
                    var filter_result = JSON.parse(data);
                    var countSelector=$("#count_value");
                    if(data != "{}")
                    count = filter_result.count;
                    var limit= (count /100);
                    countSelector.text(count);
                    $("#myBar").css("width",limit);
                    if(limit > 80){
                    countSelector.css('color','red');
                    }
                }
            });
        } catch (error) {
            console.log(error);
        }
});
</script>
{% endblock scripts %}

templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }}Profile{% endblock %}

{% block container %}
<div style="height: 100px"></div>

    <div class="container profile-head">
        <div class="row">
            <div class="col-sm-10">
                <h1>{{ show_user.get_full_name }}</h1>
                {% if editable %}
                    <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container profile-body">
        <div class="row">
            <div class="col-sm-4">
                <ul class="list-group">
                    <li class="list-group-item text-muted">Profile</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span>
                        {{ show_user.email|default:"missing" }}
                        {% if show_user.profile.email_verified %}
                            <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
                            <span class="sr-only">Verified</span>
                        {% else %}
                            <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
                            <span class="sr-only">Not Verified</span>
                        {% endif %}
                    </li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>

                </ul>
            </div>
            <div class="col-sm-8">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ show_user.get_full_name }}'s Profile
                        {% if show_user.profile.slug %}
                            <a href="{% url 'profiles:show' show_user.profile.slug %}">
                                <span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
                                <span class="sr-only">Permalink</span></a> {{ show_user.profile.get_absolute_url }}
                        {% else %}
                            <!--<a href="https://github.com/arocks/edge/issues/40" target="_blank"><span>No permalink. See this issue.</span></a>-->
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <strong>Bio</strong>: {{ show_user.profile.bio }}
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="panel panel-default" id="api_key_hidden" hidden>
                    <div class="panel-heading"> Api-Key
                    </div>
                    <div class="panel-body">
                    <div class="col-sm-8 " id="my_keys">
                        <strong></strong>
                    </div>

                    <div class="col-sm-4">
                    <button value="Regenrate APIKEY" onclick="regenerate_api_key()">Regenrate APIKEY</button>
                     </div>
                        </div>

                </div>
            </div>
    </div>
    </div>
    <input type="hidden" id="api_url" value="{{ api_url }}">
    <input type="hidden" id="api_host" value="{{ api_host }}">
    <input type="hidden" id="user_id" value="{{ user.id }}">


{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/common_functions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/js.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/profiles/show_profiles.js' %}"></script>

{% endblock scripts %}