brainvita_frontend/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import accounts.urls
import profiles.urls
import dashboard.urls
import mysite.urls
import delegate.urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profiles.urls, namespace='profiles')),
    url(r'^users/', include(dashboard.urls, namespace='dashboard')),
    url(r'^tester/', include(delegate.urls, namespace='tester')),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(mysite.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url

from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^home/$', views.HomeView.as_view(), name='home_view'),
    url(r'^vision/$', views.VisionView.as_view(), name='vision_view'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard_view'),
    url(r'^dashboard/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.DashboardView.as_view(), name='dashboard_view'),
    url(r'^create_test_view/$', views.CreateTestView.as_view(), name='create_test_view'),
    url(r'^create_test_view/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.CreateTestView.as_view(), name='create_test_view'),
    url(r'^project_overview/$', views.ProjectView.as_view(), name='project_overview'),
    url(r'^project_overview/(?P<project_id>[0-9]+)$', views.ProjectView.as_view(), name='test_view'),
    url(r'^add_project/$', views.AddProjectView.as_view(), name='add_project'),
    url(r'^add_project/(?P<project_id>[0-9]+)$', views.AddProjectView.as_view(), name='edit_project'),
    url(r'^add_test/$', views.AddTestView.as_view(), name='add_test'),
    url(r'^edit_test/$', views.EditTestView.as_view(), name='edit_test'),
    url(r'^add_media/(?P<project_id>[0-9]+)$', views.AddMediaView.as_view(), name='add_media'),
    url(r'^manage_project/$', views.ManageProjectView.as_view(), name='manage_project'),
    url(r'^media_overview/$', views.MediaView.as_view(), name='media_overview'),
    url(r'^media_overview_list/(?P<project_id>[0-9]+)$', views.MediaOverview.as_view(), name='media_overview_list'),
    url(r'^media_overview_report/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.MediaReportsView.as_view(), name='media_overview_report'),
    url(r'^view_reports/$', views.ReportsView.as_view(), name='view_reports'),
    url(r'^compare_reports/$', views.CompareReportsView.as_view(), name='compare_reports'),
    url(r'^track_test/(?P<project_id>[0-9]+)/(?P<media_id>[0-9]+)$', views.TestDetails.as_view(), name='track_test'),
    url(r'^uploadfile/(?P<media_id>[0-9]+)$', views.UploadFile.as_view(), name='uploadfile'),
    url(r'^s3uploadvideo/', views.S3FileUploadAPI.as_view(), name='s3uploadvideo'),
    url(r'^settings/$', views.SettingsView.as_view(), name='settings'),

]

mysite/urls.py
from django.conf.urls import include, url
from mysite.views import *
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns=[
    url(r'^$',HomePage.as_view(), name='home'),
    url(r'^sendcontactmail/$', HomePage().send_contact_mail, name='sendcontactmail'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
]

dashboard/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from authtools import forms as authtoolsforms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Field
# from dashboard.models import CreateTest
from django.core.urlresolvers import reverse

# class FileField(Field):
#     template = 'bootstrap/layout/file_field.html'


class CreateTestForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(CreateTestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['email'].widget.input_type = "text"  # ugly hack

        self.helper.layout = Layout(
            # FileField('main_image',placeholder="Enter Email", autofocus=""),
            # Field('test_image', placeholder="Enter Email", autofocus=""),
            Field('email', placeholder="Enter email", autofocus="", css_class="form-control"),

            Submit('launch', 'Launch',css_class="btn btn-lg btn-primary btn-block"),
        )
    #
    # class Meta:
    #     model = CreateTest

dashboard/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
import requests,subprocess
from rest_framework.views import APIView
from rest_framework.response import Response
import re,boto3,threading
from dashboard import forms
# USERNAME_PASSWORD = "admin:admin@123"

"""
Getting Started View to create a new application
@input application_name,category,platform,time_zone
@output project_token
"""
# User =get_user_model()

def async(function):
    def async_decorator(*args, **kwargs):
        try:
            t = threading.Thread(target=function,args=args,kwargs = kwargs)
            t.setDaemon(False)
            t.start()
        except:
            return {"status": "Unsuccesfull"}
    return async_decorator


class VisionView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/vision_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['api_host'] = settings.API_HOSTNAME
        return super(VisionView, self).get(request, *args, **kwargs)


class UploadFile(APIView):
    def post(self,request,media_id=''):
        if request.method != 'POST':
            return Response({"response":'Only POST requests are allowed'})
        file = request.FILES['filetoupload']
        file.name = filter(lambda x: str.isalnum(x) or "." == x or "-" == x or  "_" == x, file.name.encode())
        with open('static/media/%s' % str(media_id)+"_"+file.name,'wb+') as dest:
            for chunk in file.chunks():
                dest.write(chunk)
        print file.name.replace('(','\(').replace(')',"\)")
        png = "".join(file.name.split(".")[:-1])
        subprocess.call("ffmpeg -i static/media/"+str(media_id)+"_"+re.escape(file.name)+" -vcodec  png -ss 1 -vframes 1 -an -f  rawvideo static/media/"+str(media_id)+"_"+png+".png",shell=True)
        return Response({"response":'File uploaded'})
            



class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/home_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['api_host'] = settings.API_HOSTNAME
        return super(HomeView, self).get(request, *args, **kwargs)


class DashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/dashboard_view.html"

    def get(self, request, project_id='', media_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        kwargs['media_id'] = media_id
        return super(DashboardView, self).get(request, *args, **kwargs)


class CreateTestView(LoginRequiredMixin, APIView, generic.TemplateView):
    template_name = "dashboard/create_test_view.html"
    http_method_names = ['get', 'post']
    form_class = forms.CreateTestForm

    def get(self, request, project_id='', media_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        kwargs['media_id'] = media_id
        #form=self.form_class,
        return super(CreateTestView, self).get(request, *args, **kwargs)

    def post(self, request, project_id='', media_id=''):

        return redirect("dashboard:project_overview")


class TestDetails(LoginRequiredMixin, APIView, generic.TemplateView):
    template_name = "dashboard/test_details.html"
    http_method_names = ['get', 'post']
    def get(self, request, project_id='', media_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        kwargs['media_id'] = media_id
        return super(TestDetails, self).get(request, *args, **kwargs)

    def post(self, request, project_id='', media_id=''):
        return redirect("dashboard:project_overview")



class ProjectView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/project_view.html"

    def get(self, request, project_id='',*args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        return super(ProjectView, self).get(request, *args, **kwargs)


class MediaView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/media_overview.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        return super(MediaView, self).get(request, *args, **kwargs)

    def post(self):
        return redirect("dashboard")


class AddMediaView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/add_media.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(AddMediaView, self).get(request, *args, **kwargs)

class MediaOverview(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/media_overview_list.html"

    def get(self, request, *args, **kwargs):
        kwargs["project_id"] = kwargs["project_id"]
        kwargs['user'] = self.request.user
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(MediaOverview, self).get(request, *args, **kwargs)


class MediaReportsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/media_overview_report.html"

    def get(self, request, *args, **kwargs):
        kwargs["project_id"] = kwargs["project_id"]
        kwargs["media_id"] = kwargs["media_id"]
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(MediaReportsView, self).get(request, *args, **kwargs)


class ReportsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/reports_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        return super(ReportsView, self).get(request, *args, **kwargs)


class CompareReportsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/compare_reports_view.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        return super(CompareReportsView, self).get(request, *args, **kwargs)


class SettingsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/settings.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        return super(SettingsView, self).get(request, *args, **kwargs)

class ManageProjectView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/manage_projects.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        return super(ManageProjectView, self).get(request, *args, **kwargs)

class AddProjectView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/add_project.html"

    def get(self, request,project_id='', *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = project_id
        return super(AddProjectView, self).get(request, *args, **kwargs)

class AddTestView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/add_test.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['project_id'] = request.GET.get('project_id')
        return super(AddTestView, self).get(request, *args, **kwargs)


class EditTestView(LoginRequiredMixin, APIView, generic.TemplateView):
    template_name = "dashboard/edit_test.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs['media_id'] = request.GET.get('media_id')
        kwargs['project_id'] = request.GET.get('project_id')
        kwargs['activity_type'] = request.GET.get('activity_type')
        return super(EditTestView, self).get(request, *args, **kwargs)


class TrackTestView(LoginRequiredMixin, generic.TemplateView):
    template_name = "dashboard/test_details.html"

    def get(self, request, *args, **kwargs):
        kwargs['user'] = self.request.user
        kwargs['api_url'] = settings.API_ENDPOINT
        kwargs['host_url'] = settings.API_HOSTNAME
        kwargs["project_id"] = kwargs["project_id"]
        kwargs["media_id"] = kwargs["media_id"]
        return super(TrackTestView, self).get(request, *args, **kwargs)


class S3FileUploadAPI(APIView):

    def __init__(self):
        self.s3 = boto3.resource('s3')
        self.client = boto3.client('s3')

    def common_read(self,bucket,prefix,filename):
        try :
            bucket = self.s3.Bucket(bucket)
            prefix = prefix.strip().rstrip('/')

templates/dashboard/add_media.html
{% extends 'dashboard/template.html' %}
{% load staticfiles %}
{% block css %}
{% endblock %}
{% block container %}
    <div class="col-md-6">
    <h1>Create Media</h1>
    <form method="POST" name="create_media" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" value="{{ user.id }}" id="user_id">
        <input type="hidden" value="{{ project_id }}" name="project" id="project">
        <div class="input-group">
            <span class="input-group-addon" id="medianame-addon">Media Name:</span>
            <input type="text" class="form-control" required="" name="name" id="name" placeholder="Enter Media Name" aria-describedby="medianame-addon">
        </div>
        <br>
        <div class="input-group">
            <span class="input-group-addon" id="mediaversion-addon">Media Version:</span>
            <input type="text" class="form-control" required="" name="media_version" id="version" placeholder="Enter Media Version" aria-describedby="mediaversion-addon">
        </div>
        <br>
        <div class="input-group">
            <span class="input-group-addon" id="fileType-addon">File Type:</span>
            <select id="selectionType" name="file_location" class="form-control" aria-describedby="fileType-addon">
                <option value="0">Please select option</option>
                <option value="1">Local Drive</option>
                <option value="2">Network</option>
            </select>
        </div>
        <br>

        <input class="localDrive form-control" type="file" id="localDrivePath" >
        <br>
        <div class="input-group">
            <span class="input-group-addon networkDrive" id="networkDrive-addon">URL:</span>
            <input type="text" class="form-control networkDrive" name="url" id="networkDrivePath" aria-describedby="networkDrive-addon">
        </div>
        <label> Video Preview</label>
        <video src="" height="200px" width="640px" controls></video>
        <label id="error_message" class="error"></label>
        <br>
        <a href="{% url "dashboard:manage_project" %}" class="btn btn-inline cancel_btn">Cancel</a>
        <input type="submit" class="btn btn-primary btn-inline success_btn" value="Create">
        <input type="hidden" id="api_url" value="{{ api_url }}">
        <div class="success_message"></div>
    </form>
    </div>
    <div class="col-md-3"></div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/common_functions.js' %}"></script>
    <script type="text/javascript">
    $(function () {
        var api_host = $("#api_url").val();
        var form = $("form[name='create_media']");
        var ajax_url = api_host+"dashboard/add_media/";

        form.on("submit",function (event) {
            event.preventDefault();
            var formData = new FormData($(this)[0]);
            $.ajax({
                url: ajax_url,
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                async: false,
                success: function (data) {
                    if(data.status == "inserted")
                    {
                        $(".success_message").text("Media Created Successfully");
                        window.location = "/users/manage_project/";
                    }
                }
            });
            return false;
        });
    });
    (function localFileVideoPlayer() {
        'use strict'
        var URL = window.URL || window.webkitURL
        var displayMessage = function (message, isError) {
            var element = document.querySelector('#error_message')
            element.innerHTML = message
            element.className = isError ? 'error' : 'info'
        }
        var playLocalDriveSelectedFile = function (event) {
            var file = this.files[0]
            var type = file.type
            var videoNode = document.querySelector('video')
            var canPlay = videoNode.canPlayType(type)
            if (canPlay === '') canPlay = 'no'
            var message = 'Can play type "' + type + '": ' + canPlay
            var isError = canPlay === 'no'
            displayMessage(message, isError)

            if (isError) {
                return
            }
            console.log(file);
            var fileURL = URL.createObjectURL(file)
            videoNode.src = fileURL
        }
        var playNetworkDriveSelectedFile = function (event) {
            var videoNode = document.querySelector('video')
            var fileURL  = $("#networkDrivePath").val()
            videoNode.src = fileURL
        }
        var inputLocalDrivePathNode = document.querySelector('#localDrivePath')
        inputLocalDrivePathNode.addEventListener('change', playLocalDriveSelectedFile, false)
        var inputLocalDrivePathNode = document.querySelector('#networkDrivePath')
        inputLocalDrivePathNode.addEventListener('change', playNetworkDriveSelectedFile, false)
    })()
    $(function() {
        // default hide all drive input
        $(".networkDrive,.localDrive").hide();
        $("#selectionType").change(function(){
            // clean url
            $("video").attr("src",'');
            $("#error_message").text("");
            // select drop down option form network
            var selectedType = $('#selectionType :selected').val();
            switch(selectedType){
                case "1":
                    $(".localDrive").show();
                    $(".networkDrive").hide();
                    break;
                case "2":
                    $(".localDrive").hide();
                    $(".networkDrive").show();
                    break;
                default:
                    $(".networkDrive,.localDrive").hide();
                    break;
            }

        });
    })
    </script>
{% endblock %}

templates/dashboard/compare_reports_view.html
{% extends 'dashboard/template.html' %}
{% block css %}
{% endblock %}
{% block container %}
{% endblock %}
{% block js %}
     <script type="text/javascript">
    $(function () {
        if($(location).attr('pathname')== "/users/compare_reports/"){
            var selected =$("#compare_reports");
            selected.addClass("selected_url").on("click", function (event) {
                    event.preventDefault();return false;
                });
        }
    });
    </script>
{% endblock %}

templates/dashboard/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="icon" type="image/png" href="{% static 'ico/favicon.png' %}">
    <title>{% block title %} Neuro sensum {% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="description" content="{% block description %}{% endblock description %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Dashboard Page CSS -->
    <link href="{% static 'css/dashboard/new_dashboard.css' %}" rel="stylesheet">
    <!-- Icons for display -->
    <link href="{% static 'css/dashboard/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/fonts/font-awesome.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/fonts/font-awesome.min.css' %}" rel="stylesheet"> -->
    <style type="text/css">
    </style>
    {% block css %}
    {% endblock %}
</head>
<body>
<!-- Wrapper maintains the responsiveness of the website -->
<div class="wrapper">
    <!-- Sidebar decides the background and navigation links -->
    <div class="sidebar" data-background-color="white" data-active-color="danger">
    {% block sidebar %}
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="{% url 'dashboard:project_overview' %}" class="simple-text">
                        Welcome {{ user }}
                    </a>
                </div>

                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'dashboard:project_overview' %}">
                            <i class="ti-panel"></i>
                            <p>Projects</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:dashboard_view' %}">
                            <i class="ti-view-list-alt"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:settings' %}">
                            <i class="ti-pencil"></i>
                            <p>Settings</p>
                        </a>
                    </li>
                    <!-- <li>
                        <a href="{% url 'profiles:show_self' %}">
                            <i class="ti-user"></i>
                            <p>User Profile</p>
                        </a>
                    </li> -->
                    
                    <li class="active-pro">
                        <a href="{% url 'accounts:logout' %}">
                            <i class="ti-export"></i>
                            <p>Log Out</p>
                        </a>
                    </li>
                </ul>
            </div>
    {% endblock %}
    </div> <!-- end of sidebar -->
    <!-- This main panel contains the content -->
    <div class="main-panel">
        <!-- Content Header -->
        {% block contentnavbar %}
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar bar1"></span>
                            <span class="icon-bar bar2"></span>
                            <span class="icon-bar bar3"></span>
                        </button>
                        <a class="navbar-brand" href="#">{% block content_title %}{% endblock %}</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <!-- <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-panel"></i>
                                    <p>Stats</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="ti-bell"></i>
                                        <p class="notification">5</p>
                                        <p>Notifications</p>
                                        <b class="caret"></b>
                                  </a>
                                  <ul class="dropdown-menu">
                                    <li><a href="#">Notification 1</a></li>
                                    <li><a href="#">Notification 2</a></li>
                                    <li><a href="#">Notification 3</a></li>
                                    <li><a href="#">Notification 4</a></li>
                                    <li><a href="#">Another notification</a></li>
                                  </ul>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="ti-settings"></i>
                                    <p>Settings</p>
                                </a>
                            </li>
                        </ul>-->
                    </div> 
                </div>
            </nav>
        {% endblock %}
            <!-- Image loader -->
        <div id='loader'>
            <img src="{% static 'img/loading.gif' %}" width='320px' height='320px'>
        </div>
        <!-- Image loader -->
        <!-- Main Content to be displayed here -->
        {% block maincontent %}{% endblock %}
    </div> <!-- end of Main panel (right side)-->
</div> <!-- end of page wrapper-->

{% block footer %}{% endblock %}
<!-- $j is for 3.1.1 version js file-->
<!--<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript">var $j = $.noConflict(true);</script> -->
<!-- jQuery and Bootstrap plugins -->
<!-- <script type="text/javascript" src="{% static 'js/dashboard/jquery-1.10.2.js' %}"></script> -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Intended for Main Javascript logic -->
{% block js %}{% endblock %}
<script type="text/javascript" src="{% static 'js/dashboard/new_dashboard.js' %}"></script>
</body>
</html>

templates/dashboard/reports_view.html
{% extends 'dashboard/template.html' %}
{% block css %}
{% endblock %}
{% block container %}
{% endblock %}
{% block js %}
    <script type="text/javascript">
    $(function () {
        if($(location).attr('pathname')== "/users/view_reports/"){
            var selected =$("#view_reports");
            selected.addClass("selected_url").on("click", function (event) {
                    event.preventDefault();return false;
                });
        }
    });
    </script>
{% endblock %}